#import <MediaPipeTasksVision/MPPBaseOptions.h>
#import <MediaPipeTasksVision/MPPCategory.h>
#import <MediaPipeTasksVision/MPPClassificationResult.h>
#import <MediaPipeTasksVision/MPPClassifierOptions.h>
#import <MediaPipeTasksVision/MPPCommon.h>
#import <MediaPipeTasksVision/MPPConnection.h>
#import <MediaPipeTasksVision/MPPDetection.h>
#import <MediaPipeTasksVision/MPPFaceDetector.h>
#import <MediaPipeTasksVision/MPPFaceDetectorOptions.h>
#import <MediaPipeTasksVision/MPPFaceDetectorResult.h>
#import <MediaPipeTasksVision/MPPFaceLandmarker.h>
#import <MediaPipeTasksVision/MPPFaceLandmarkerOptions.h>
#import <MediaPipeTasksVision/MPPFaceLandmarkerResult.h>
#import <MediaPipeTasksVision/MPPGestureRecognizer.h>
#import <MediaPipeTasksVision/MPPGestureRecognizerOptions.h>
#import <MediaPipeTasksVision/MPPGestureRecognizerResult.h>
#import <MediaPipeTasksVision/MPPHandLandmarker.h>
#import <MediaPipeTasksVision/MPPHandLandmarkerOptions.h>
#import <MediaPipeTasksVision/MPPHandLandmarkerResult.h>
#import <MediaPipeTasksVision/MPPImage.h>
#import <MediaPipeTasksVision/MPPImageClassifier.h>
#import <MediaPipeTasksVision/MPPImageClassifierOptions.h>
#import <MediaPipeTasksVision/MPPImageClassifierResult.h>
#import <MediaPipeTasksVision/MPPLandmark.h>
#import <MediaPipeTasksVision/MPPObjectDetector.h>
#import <MediaPipeTasksVision/MPPObjectDetectorOptions.h>
#import <MediaPipeTasksVision/MPPObjectDetectorResult.h>
#import <MediaPipeTasksVision/MPPRunningMode.h>
#import <MediaPipeTasksVision/MPPTaskOptions.h>
#import <MediaPipeTasksVision/MPPTaskResult.h>
#import <MediaPipeTasksVision/MPPBaseOptions.h>
#import <MediaPipeTasksVision/MPPCategory.h>
#import <MediaPipeTasksVision/MPPClassificationResult.h>
#import <MediaPipeTasksVision/MPPClassifierOptions.h>
#import <MediaPipeTasksVision/MPPCommon.h>
#import <MediaPipeTasksVision/MPPConnection.h>
#import <MediaPipeTasksVision/MPPDetection.h>
#import <MediaPipeTasksVision/MPPFaceDetector.h>
#import <MediaPipeTasksVision/MPPFaceDetectorOptions.h>
#import <MediaPipeTasksVision/MPPFaceDetectorResult.h>
#import <MediaPipeTasksVision/MPPFaceLandmarker.h>
#import <MediaPipeTasksVision/MPPFaceLandmarkerOptions.h>
#import <MediaPipeTasksVision/MPPFaceLandmarkerResult.h>
#import <MediaPipeTasksVision/MPPGestureRecognizer.h>
#import <MediaPipeTasksVision/MPPGestureRecognizerOptions.h>
#import <MediaPipeTasksVision/MPPGestureRecognizerResult.h>
#import <MediaPipeTasksVision/MPPHandLandmarker.h>
#import <MediaPipeTasksVision/MPPHandLandmarkerOptions.h>
#import <MediaPipeTasksVision/MPPHandLandmarkerResult.h>
#import <MediaPipeTasksVision/MPPImage.h>
#import <MediaPipeTasksVision/MPPImageClassifier.h>
#import <MediaPipeTasksVision/MPPImageClassifierOptions.h>
#import <MediaPipeTasksVision/MPPImageClassifierResult.h>
#import <MediaPipeTasksVision/MPPLandmark.h>
#import <MediaPipeTasksVision/MPPObjectDetector.h>
#import <MediaPipeTasksVision/MPPObjectDetectorOptions.h>
#import <MediaPipeTasksVision/MPPObjectDetectorResult.h>
#import <MediaPipeTasksVision/MPPRunningMode.h>
#import <MediaPipeTasksVision/MPPTaskOptions.h>
#import <MediaPipeTasksVision/MPPTaskResult.h>
#import <MediaPipeTasksVision/MPPBaseOptions.h>
#import <MediaPipeTasksVision/MPPCategory.h>
#import <MediaPipeTasksVision/MPPClassificationResult.h>
#import <MediaPipeTasksVision/MPPClassifierOptions.h>
#import <MediaPipeTasksVision/MPPCommon.h>
#import <MediaPipeTasksVision/MPPConnection.h>
#import <MediaPipeTasksVision/MPPDetection.h>
#import <MediaPipeTasksVision/MPPFaceDetector.h>
#import <MediaPipeTasksVision/MPPFaceDetectorOptions.h>
#import <MediaPipeTasksVision/MPPFaceDetectorResult.h>
#import <MediaPipeTasksVision/MPPFaceLandmarker.h>
#import <MediaPipeTasksVision/MPPFaceLandmarkerOptions.h>
#import <MediaPipeTasksVision/MPPFaceLandmarkerResult.h>
#import <MediaPipeTasksVision/MPPGestureRecognizer.h>
#import <MediaPipeTasksVision/MPPGestureRecognizerOptions.h>
#import <MediaPipeTasksVision/MPPGestureRecognizerResult.h>
#import <MediaPipeTasksVision/MPPHandLandmarker.h>
#import <MediaPipeTasksVision/MPPHandLandmarkerOptions.h>
#import <MediaPipeTasksVision/MPPHandLandmarkerResult.h>
#import <MediaPipeTasksVision/MPPImage.h>
#import <MediaPipeTasksVision/MPPImageClassifier.h>
#import <MediaPipeTasksVision/MPPImageClassifierOptions.h>
#import <MediaPipeTasksVision/MPPImageClassifierResult.h>
#import <MediaPipeTasksVision/MPPLandmark.h>
#import <MediaPipeTasksVision/MPPObjectDetector.h>
#import <MediaPipeTasksVision/MPPObjectDetectorOptions.h>
#import <MediaPipeTasksVision/MPPObjectDetectorResult.h>
#import <MediaPipeTasksVision/MPPRunningMode.h>
#import <MediaPipeTasksVision/MPPTaskOptions.h>
#import <MediaPipeTasksVision/MPPTaskResult.h>
